theme = "gruvbox"

[editor]
true-color = true
line-number = "relative"

[editor.indent-guides]
render = true
color-modes = true

[keys.normal]
";" = "command_mode"
"space"= { w = ":w", ";" = "buffer_picker", "c" = ":clipboard-yank" }
"K" = "hover"

[keys.insert]
"C-space" = "completion"
"C-j" = "normal_mode"
